name: Build

on:
  push:
    branches: 
      - "*"
  pull_request:
    branches: 
      - "*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Download Rust Nightly
      run: rustup install nightly
    - name: Build
      run: cargo +nightly build --verbose --all-packages
