name: Build

on:
  push:
    branches: 
      - "*"
  pull_request:
    branches: 
      - "*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Download Rust nightly
      run: rustup install nightly-2024-04-24

    - name: Build
      run: cargo build --verbose

    - name: Download VC redistributables
      run: Invoke-WebRequest -Uri "https://aka.ms/vs/17/release/vc_redist.x64.exe" -OutFile "vc_redist.x64.exe"

    - name: Build installer 
      uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
      with:
        path: build.iss 
        options: /O+

    - uses: actions/upload-artifact@v4
      with:
        name: instigator.exe
        path: target\release\instigator.exe
    
    - name: Upload installer
      run: ls

    