name: Build

on:
  push:
    branches: 
      - "*"
  pull_request:
    branches: 
      - "*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Download Rust Nightly
      run: rustup install nightly-2024-04-24
    - name: Build
      run: cargo build --verbose
